class Chord {
  final String chordName;
  final String assetImagePath;
  Chord({required this.chordName, required this.assetImagePath});
}

List<Chord> allChords = [
  Chord(chordName: 'A', assetImagePath: 'assets/chords/A.png'),

  Chord(chordName: 'A7', assetImagePath: 'assets/chords/A7.png'),
  Chord(chordName: 'Asus2', assetImagePath: 'assets/chords/Asus2.png'),
  Chord(chordName: 'Asus4', assetImagePath: 'assets/chords/Asus4.png'),
  Chord(chordName: 'A7sus4', assetImagePath: 'assets/chords/A7sus4.png'),
  Chord(chordName: 'A7sus2', assetImagePath: 'assets/chords/A7sus2.png'),
  Chord(chordName: 'A°7', assetImagePath: 'assets/chords/A°7.png'),
  Chord(chordName: 'Am7', assetImagePath: 'assets/chords/Am7.png'),
  Chord(chordName: 'A5', assetImagePath: 'assets/chords/A5.png'),
  Chord(chordName: 'A6', assetImagePath: 'assets/chords/A6.png'),
  Chord(chordName: 'A6add9', assetImagePath: 'assets/chords/A6add9.png'),
  Chord(chordName: 'A7-5', assetImagePath: 'assets/chords/A7-5.png'),
  Chord(chordName: 'A7+5', assetImagePath: 'assets/chords/A7+5.png'),
  Chord(chordName: 'A7-9', assetImagePath: 'assets/chords/A7-9.png'),
  Chord(chordName: 'A7+9', assetImagePath: 'assets/chords/A7+9.png'),
  Chord(chordName: 'A9', assetImagePath: 'assets/chords/A9.png'),
  Chord(chordName: 'A11', assetImagePath: 'assets/chords/A11.png'),
  Chord(chordName: 'A13', assetImagePath: 'assets/chords/A13.png'),
  Chord(chordName: 'Aadd9', assetImagePath: 'assets/chords/Aadd9.png'),
  Chord(chordName: 'Am(maj7)', assetImagePath: 'assets/chords/Am(maj7).png'),
  Chord(chordName: 'Am6add9', assetImagePath: 'assets/chords/Am6add9.png'),
  Chord(chordName: 'Am9', assetImagePath: 'assets/chords/Am9.png'),
  Chord(chordName: 'Amadd9', assetImagePath: 'assets/chords/Amadd9.png'),
  Chord(chordName: 'Amaj7-5', assetImagePath: 'assets/chords/Amaj7-5.png'),
  Chord(chordName: 'Amaj7+5', assetImagePath: 'assets/chords/Amaj7+5.png'),
  Chord(chordName: 'Amaj9', assetImagePath: 'assets/chords/Amaj9.png'),

  Chord(chordName: 'Am6', assetImagePath: 'assets/chords/Am6.png'),
  Chord(chordName: 'Amaj7', assetImagePath: 'assets/chords/Amaj7.png'),
  Chord(chordName: 'A°', assetImagePath: 'assets/chords/A°.png'),
  Chord(chordName: 'Am', assetImagePath: 'assets/chords/Am.png'),
  Chord(chordName: 'A+', assetImagePath: 'assets/chords/A+.png'),
  Chord(chordName: 'B', assetImagePath: 'assets/chords/B.png'),
  Chord(chordName: 'C', assetImagePath: 'assets/chords/C.png'),
  Chord(chordName: 'Cm', assetImagePath: 'assets/chords/Cm.png'),
  Chord(chordName: 'C7', assetImagePath: 'assets/chords/C7.png'),
  Chord(chordName: 'Cm7', assetImagePath: 'assets/chords/Cm7.png'),
  Chord(chordName: 'C+', assetImagePath: 'assets/chords/C+.png'),
  Chord(chordName: 'Cadd9', assetImagePath: 'assets/chords/Cadd9.png'),
  Chord(chordName: 'Cm6add9', assetImagePath: 'assets/chords/Cm6add9.png'),
  Chord(chordName: 'Dm', assetImagePath: 'assets/chords/Dm.png'),
  Chord(chordName: 'D', assetImagePath: 'assets/chords/D.png'),
  Chord(chordName: 'D7', assetImagePath: 'assets/chords/D7.png'),
  Chord(chordName: 'Dsus4', assetImagePath: 'assets/chords/Dsus4.png'),
  Chord(chordName: 'D+', assetImagePath: 'assets/chords/D+.png'),
  Chord(chordName: 'E', assetImagePath: 'assets/chords/E.png'),
  Chord(chordName: 'Em', assetImagePath: 'assets/chords/Em.png'),
  Chord(chordName: 'E7', assetImagePath: 'assets/chords/E7.png'),
  Chord(chordName: 'Esus2', assetImagePath: 'assets/chords/Esus2.png'),
  Chord(chordName: 'E+', assetImagePath: 'assets/chords/E+.png'),
  Chord(chordName: 'F', assetImagePath: 'assets/chords/F.png'),
  Chord(chordName: 'Fm', assetImagePath: 'assets/chords/Fm.png'),
  Chord(chordName: 'F7', assetImagePath: 'assets/chords/F7.png'),
  Chord(chordName: 'G', assetImagePath: 'assets/chords/G.png'),
  Chord(chordName: 'Gm', assetImagePath: 'assets/chords/Gm.png'),
  Chord(chordName: 'G7', assetImagePath: 'assets/chords/G7.png'),
  Chord(chordName: 'Gadd9', assetImagePath: 'assets/chords/Gadd9.png'),
  Chord(chordName: 'Bm9', assetImagePath: 'assets/chords/Bm9.png'),
  Chord(chordName: 'B7', assetImagePath: 'assets/chords/B7.png'),
  Chord(chordName: 'Bbm', assetImagePath: 'assets/chords/Bbm.png'),
  Chord(chordName: 'Bb', assetImagePath: 'assets/chords/Bb.png'),
  Chord(chordName: 'Bb7', assetImagePath: 'assets/chords/Bb7.png'),
  Chord(chordName: 'Bb+', assetImagePath: 'assets/chords/Bb+.png'),
  Chord(chordName: 'Bbsus4', assetImagePath: 'assets/chords/Bbsus4.png'),
  Chord(chordName: 'Bbsus2', assetImagePath: 'assets/chords/Bbsus2.png'),
];
Map<String, String> chordImageMap = {
  for (final chord in allChords) chord.chordName: chord.assetImagePath,
};

List<String> allChordNames = allChords.map((chord) => chord.chordName).toList();
